// SPDX-License-Idenitifier: MIT

// Documenbtation.
// https://docs.chain.link/chainlink-automation/guides/compatible-contracts

pragma solidity ^0.8.0;

// Use the AutomationCompatibleInterface from the library to ensure your checkUpkeep and performUpkeep function definitions match the definitions expected by the Chainlink Automation Network
import {
    AutomationCompatibleInterface
} from "chainlink-brownie-contracts/contracts/src/v0.8/automation/AutomationCompatible.sol";

contract CustomLogicCounterTrigger is AutomationCompatibleInterface {
    /**
     * @notice the state to be updated on diffrent intervals.
     */
    uint256 public counter;

    /**
     * @notice the interval after which the state must be updated/counter increased.
     */
    uint256 public immutable interval;

    /**
     * @notice the last timeestamp the status was updated/the counter increased.
     */
    uint256 public lastTimeStamp;

    /**
     * A simple constructor.
     * @param updateInterval thee interval in seconds after which the state/counter is updated.
     */
    constructor(uint256 updateInterval) {
        interval = updateInterval;
        lastTimeStamp = block.timestamp;

        counter = 0;
    }

    /**
     * Checks if the state of the blockchain/smart contract warants upkeep.
     * param checkData cheeckData defined whwn the upkeep is registered.
     * @return upkeepNeeded true if there is  need to update the state/counter.
     * which invlolves calling perform upkeep.
     * @return The performData is generated by the Automation Node's call to your checkUpkeep function
     *
     */
    function checkUpkeep(
        bytes calldata /* checkData */
    )
        external
        view
        override
        returns (
            bool upkeepNeeded,
            bytes memory /* performData */
        )
    {
        upkeepNeeded = (block.timestamp - lastTimeStamp) > interval;
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata) external override {
        if ((block.timestamp - lastTimeStamp) > interval) {
            lastTimeStamp = block.timestamp;

            counter = counter + 1;
        }
        // We don't use the performData in this example. The performData is generated by the Automation Node's call to your
        // checkUpkeep function
    }

    /**
     * Get how many times the counter has run.
     */
    function getCount() external view returns (uint256) {
        return counter;
    }
}
